apiVersion: v1
kind: Service
metadata:
  name: stable-diffusion-nginx-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}' # Creates a NEG after an Ingress is created
    beta.cloud.google.com/backend-config: '{"default": "config-default"}'
  labels:
    app: stable-diffusion-nginx
spec:
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: stable-diffusion-nginx
  type: ClusterIP