apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: simple-sd-server
spec:
  replicas: 1
  template:
    spec:
      container: simple-game-server
      ports:
      - name: default
        container: simple-game-server
        containerPort: 7654
      - name: sd
        container: stable-diffusion-webui
        containerPort: 7860
        protocol: TCP
      template:
        spec:
          containers:
          - name: simple-game-server
            image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.14
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
          - name: stable-diffusion-webui
            image: us-central1-docker.pkg.dev/dave-selfstudy01/hzchen-repo/sd-webui:train
            command: ["python3"]
            args:
            - "webui.py"
            - "--listen"
            - "--xformers"
            - "--medvram"
            - "--no-gradio-queue"
            resources:
              limits:
                nvidia.com/gpu: "1"
            volumeMounts:
                # name must match the volume name below
                - name: nfs
                  mountPath: "/stable-diffusion-webui/outputs/"            
          volumes:
          - name: nfs
            persistentVolumeClaim:
              claimName: nfs
