---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs
spec:
  selector:
    matchLabels:
      app: ngx-scheduler
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs
