apiVersion: "agones.dev/v1"
kind: Fleet
metadata:
  name: sd-agones-fleet
spec:
  replicas: 1
  template:
    spec:
      container: simple-game-server
      ports:
      - name: default
        container: simple-game-server
        containerPort: 7654
      - name: sd
        container: stable-diffusion-webui
        containerPort: 7860
        protocol: TCP
      template:
        spec:
          containers:
          - name: simple-game-server
            image: us-docker.pkg.dev/agones-images/examples/simple-game-server:0.14
            resources:
              requests:
                memory: "64Mi"
                cpu: "20m"
              limits:
                memory: "64Mi"
                cpu: "20m"
          - name: stable-diffusion-webui
            image: waangjie/stable-diffusion-webui:inferencev1
            command: ["/bin/sh", "start.sh"]
            volumeMounts:
            - name: stable-diffusion-storage
              mountPath: "/stable-diffusion-webui/outputs/"
            resources:
              limits:
                nvidia.com/gpu: "1"
          volumes:
            - name: stable-diffusion-storage
              persistentVolumeClaim:
                claimName: vol1