steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-central1-docker.pkg.dev/argolis-lsj-test/sd-lsj/sd-peft:v1', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/argolis-lsj-test/sd-lsj/sd-peft:v1']
options:
  machineType: 'N1_HIGHCPU_8'
  diskSizeGb: '200'