workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-8
    acceleratorType: NVIDIA_TESLA_V100
    acceleratorCount: 1
  replicaCount: 1
  containerSpec:
    imageUri: us-central1-docker.pkg.dev/argolis-lsj-test/sd-lsj/sd-peft:v1