apiVersion: apps/v1
kind: Deployment
metadata:
  name: stable-diffusion-nai-deployment
  labels:
    app: stable-diffusion-nai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stable-diffusion-nai
  template:
    metadata:
      labels:
        app: stable-diffusion-nai
    spec:
      nodeSelector:
        cloud.google.com/gke-gpu-sharing-strategy: time-sharing
        cloud.google.com/gke-max-shared-clients-per-gpu: "2"
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            preference:
              matchExpressions:
              - key: cloud.google.com/gke-spot
                operator: In
                values:
                - "true"
      volumes:
        - name: stable-diffusion-storage
          persistentVolumeClaim:
            claimName: vol2
      containers:
      - name: stable-diffusion-webui
        image: us-central1-docker.pkg.dev/dave-selfstudy01/hzchen-repo/sd-webui:inference
        resources:
          limits:
            cpu: 1800m
            memory: 23Gi
            nvidia.com/gpu: 1
        ports:
          - containerPort: 7860
        volumeMounts:
          - mountPath: "/stable-diffusion-webui/models/Stable-diffusion"
            name: stable-diffusion-storage
            subPath: models/Stable-diffusion/nai
          - mountPath: "/stable-diffusion-webui/models/Lora"
            name: stable-diffusion-storage
            subPath: models/Lora
          - mountPath: "/stable-diffusion-webui/outputs"
            name: stable-diffusion-storage
            subPath: outputs
          - mountPath: "/stable-diffusion-webui/models/ControlNet"
            name: stable-diffusion-storage
            subPath: models/ControlNet
